version: '3'

services:
  postgresql:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASS}
      POSTGRES_DB: ${SQL_BASE}
    volumes: 
      - ./volumes/db:/var/lib/postgresql/data

  hmdm:
    image: headwindmdm/hmdm:0.1.5
    ports:
      - 10000:8080  # Используем порт 10000 вместо HTTPS
    environment:
      SQL_HOST: ${SQL_HOST}   # Используем внешний PostgreSQL
      SQL_USER: ${SQL_USER}
      SQL_BASE: ${SQL_BASE}
      SQL_PASS: ${SQL_PASS}
      PROTOCOL: http  # Принудительно включаем HTTP
      PORT: 10000     # Добавляем переменную порта
